### ISSUE TITLE
The doc navigation does not work

### ISSUE THREAD

**Issue by tiavina-mika** [TanStack/router#1169] opened 2024-02-10 16:41 UTC
### Describe the bug

the docs website always redirect to https://tanstack.com/router/v1/docs/framework/react/overview

### Your Example Website or App

https://tanstack.com/router/v1/docs/framework/react/overview

### Steps to Reproduce the Bug or Issue

1. Go to https://tanstack.com/router/v1/docs/framework/react/overview
2. search any text
3. Tap "enter"

### Expected behavior

Go to the excepted url

### Platform

- OS: Windows
- Browser: Chrome

**Comment by pjamrozowicz** [comment] 2024-02-11 18:25
Duplicate of https://github.com/TanStack/router/issues/1120

**Closed** 2024-02-11 18:39 UTC
