### ISSUE TITLE
Update from ReactRouter 1.53.1 to 1.56.1 broke types

### ISSUE THREAD

**Issue by mathewcst** [TanStack/router#2276] opened 2024-09-06 13:16 UTC
### Which project does this relate to?

Router

### Describe the bug

Each new PR at work I run a ncu (npm-check-updates) and update all packages.

This morning, after updating Tanstack Router, Typescript start complaining about Route types and won't build.

![Image](https://github.com/user-attachments/assets/198a5e89-ef15-4a98-837a-af2464f75381)

At the same time, in the main.tsx file, `createRouter` is also complaining about types:

![Image](https://github.com/user-attachments/assets/558d007c-e364-4486-92f8-0a744922aeaf)

The update:
```
- @tanstack/react-router 1.53.1
+ @tanstack/react-router 1.56.1
- @tanstack/router-devtools 1.53.1
+ @tanstack/router-devtools 1.56.1
- @tanstack/router-plugin 1.55.0
+ @tanstack/router-plugin 1.56.1
```

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-mgt3fs?file=src%2Froutes%2Ftest.tsx

### Steps to Reproduce the Bug or Issue

Unfortunately I couldn't reproduce the error on StackBlitz.

### Expected behavior

Route types still work as in previous versions

### Screenshots or Videos

![Image](https://github.com/user-attachments/assets/5d104383-61c1-45b2-a462-37fc3b9d5d59)

![Image](https://github.com/user-attachments/assets/158168c9-a941-4c5d-af1e-fe19ac155b4a)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by chorobin** [comment] 2024-09-06 13:38
Do you have declaration or composite set to true in tsconfig?

**Comment by mathewcst** [comment] 2024-09-06 13:39
@chorobin yes, composite is set to true. Here's the tsconfig:

```json
{
	"compilerOptions": {
		"composite": true,
		"tsBuildInfoFile": "./node_modules/.tmp/tsconfig.app.tsbuildinfo",
		"target": "ES2021",
		"useDefineForClassFields": true,
		"lib": [
			"ES2021",
			"DOM",
			"DOM.Iterable"
		],
		"module": "ESNext",
		"skipLibCheck": true,
		/* Bundler mode */
		"moduleResolution": "bundler",
		"allowImportingTsExtensions": true,
		"resolveJsonModule": true,
		"isolatedModules": true,
		"moduleDetection": "force",
		"noEmit": true,
		"jsx": "react-jsx",
		/* Linting */
		"strict": true,
		"noUnusedLocals": true,
		"noUnusedParameters": true,
		"noFallthroughCasesInSwitch": true,
		/* Path Alias */
		"baseUrl": "./",
		"paths": {
			"@/*": [
				"src/*"
			]
		},
		"types": [
			"@vitest/browser/providers/playwright"
		]
	},
	"include": [
		"src",
	],
}
```

**Comment by chorobin** [comment] 2024-09-06 13:42
> [@chorobin](https://github.com/chorobin) yes, composite is set to true. Here's the tsconfig:
> 
> {
> 	"compilerOptions": {
> 		"composite": true,
> 		"tsBuildInfoFile": "./node_modules/.tmp/tsconfig.app.tsbuildinfo",
> 		"target": "ES2021",
> 		"useDefineForClassFields": true,
> 		"lib": [
> 			"ES2021",
> 			"DOM",
> 			"DOM.Iterable"
> 		],
> 		"module": "ESNext",
> 		"skipLibCheck": true,
> 		/* Bundler mode */
> 		"moduleResolution": "bundler",
> 		"allowImportingTsExtensions": true,
> 		"resolveJsonModule": true,
> 		"isolatedModules": true,
> 		"moduleDetection": "force",
> 		"noEmit": true,
> 		"jsx": "react-jsx",
> 		/* Linting */
> 		"strict": true,
> 		"noUnusedLocals": true,
> 		"noUnusedParameters": true,
> 		"noFallthroughCasesInSwitch": true,
> 		/* Path Alias */
> 		"baseUrl": "./",
> 		"paths": {
> 			"@/*": [
> 				"src/*"
> 			]
> 		},
> 		"types": [
> 			"@vitest/browser/providers/playwright"
> 		]
> 	},
> 	"include": [
> 		"src",
> 	],
> }

Does it work when set to false? This is an issue on our side because we are not exporting some types from the route tree

**Comment by mathewcst** [comment] 2024-09-06 13:46
Although it solves the problem for the `main.tsx` file `const router`, the internal files still have the same problem.

```
'Route' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.ts(7022)
```

**Comment by chorobin** [comment] 2024-09-06 13:51
Does throwing the redirect work instead?

**Comment by mathewcst** [comment] 2024-09-06 13:52
Weirdly enough it does lol

**Comment by mathewcst** [comment] 2024-09-06 13:53
Shouldn't that be documented somewhere? To turn off `composite` + redirects should be thrown instead of return?

I would argue that's a breaking change.

**Comment by christopherschroer** [comment] 2024-09-06 13:54
@chorobin The `rootRouteId` value is not a valid value to pass to `getRouteApi` anymore after the update

**Comment by chorobin** [comment] 2024-09-06 13:55
`composite` is s bug. Throwing a `redirect` is the recommended way to go now. But it looks like TS now probably gets into a inference issue so it's also a bug

**Comment by christopherschroer** [comment] 2024-09-06 13:58
Also, get the errors like the one below when passing the `Link` component from TanStack Router to Material UI's `component` prop in any of their components after the update

```
error TS2769: No overload matches this call.
  Overload 1 of 3, '(props: { href: string; } & TabOwnProps & Omit<ButtonBaseOwnProps, "classes"> & CommonProps & Omit<Omit<DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>, "ref"> & { ...; }, "sx" | ... 21 more ... | "wrapped">): Element', gave the following error.
    Type '{ component: LinkComponent<"a">; label: string; search: { tab: 0; }; value: 0; }' is not assignable to type 'IntrinsicAttributes & { href: string; } & TabOwnProps & Omit<ButtonBaseOwnProps, "classes"> & CommonProps & Omit<...>'.
      Property 'component' does not exist on type 'IntrinsicAttributes & { href: string; } & TabOwnProps & Omit<ButtonBaseOwnProps, "classes"> & CommonProps & Omit<...>'.
  Overload 2 of 3, '(props: { component: LinkComponent<"a">; } & TabOwnProps & Omit<ButtonBaseOwnProps, "classes"> & CommonProps & Omit<...>): Element | null', gave the following error.
    Object literal may only specify known properties, and 'tab' does not exist in type 'ParamsReducerFn<Router<RootRoute<undefined, RouterContext, AnyContext, ({ context: { oktaAuth }, location: { pathname } }: BeforeLoadContextOptions<any, undefined, {}, RouterContext, AnyContext>) => Promise<...>, {}, undefined, RootRouteChildren, FileRouteTypes>, TrailingSlashOption, Record<...>, Record<...>>, "SEAR...'.
  Overload 3 of 3, '(props: DefaultComponentProps<ExtendButtonBaseTypeMap<TabTypeMap<{}, "div">>>): Element | null', gave the following error.
    Type '{ component: LinkComponent<"a">; label: string; search: { tab: 0; }; value: 0; }' is not assignable to type 'IntrinsicAttributes & TabOwnProps & Omit<ButtonBaseOwnProps, "classes"> & CommonProps & Omit<Omit<...> & { ...; }, "sx" | ... 21 more ... | "wrapped">'.
      Property 'component' does not exist on type 'IntrinsicAttributes & TabOwnProps & Omit<ButtonBaseOwnProps, "classes"> & CommonProps & Omit<Omit<...> & { ...; }, "sx" | ... 21 more ... | "wrapped">'.

**Comment by mathewcst** [comment] 2024-09-06 14:00
Yeah was about to say that that, not only the route types broke but apparently search also broke:

```
Type '{ search: string | undefined; action?: string | undefined; redirect?: string | undefined; }' is not assignable to type 'never'.

47    search: (old) => ({
```

**Comment by mathewcst** [comment] 2024-09-06 14:02
> [@chorobin](https://github.com/chorobin) The `rootRouteId` value is not a valid value to pass to `getRouteApi` anymore after the update

It's the exact same problem I'm facing for search when using getRouteApi

**Comment by chorobin** [comment] 2024-09-06 14:27
When using `search` are you using `to` or `from`?

**Comment by chorobin** [comment] 2024-09-06 14:27
> > [@chorobin](https://github.com/chorobin) The `rootRouteId` value is not a valid value to pass to `getRouteApi` anymore after the update
> 
> It's the exact same problem I'm facing for search when using getRouteApi

Also a bug

**Comment by christopherschroer** [comment] 2024-09-06 14:36
> When using `search` are you using `to` or `from`?

I was using `to` and `search`

**Comment by chorobin** [comment] 2024-09-06 14:39
Reproducers will be helpful. This usually happens when the types cannot resolve the route correctly

**Comment by schiller-manuel** [comment] 2024-09-07 05:25
can you please test if this PR fixes your issue? #2282 

you can install the PR built packages using e.g.

```
pnpm add https://pkg.pr.new/@tanstack/react-router@2282
pnpm add https://pkg.pr.new/@tanstack/router-generator@2282
```

then regenerate the route tree and rebuild

**Comment by kisonay** [comment] 2024-09-07 13:04
Still having the same issue with throwing a redirect:

``` 
Type "/login" is not assignable to type "." | ".." | undefined
link. d. ts(44, 5): The expected type comes from property to which is declared here on type

**Comment by schiller-manuel** [comment] 2024-09-07 13:09
@kisonay can you please provide a reproducer?

**Comment by kisonay** [comment] 2024-09-07 13:11
> [@kisonay](https://github.com/kisonay) can you please provide a reproducer?

I'll see what I can do... working in a monorepo so will need to pull things out.

**Comment by christopherschroer** [comment] 2024-09-07 13:16
It partially fixes the problems. I no longer get an error when passing `rootRouteId` to `getRouteApi`. However, I am still getting errors when passing the Link component to a Material UI component's `component` prop.


```tsx
import Button from "@mui/material/Button";
import { Link } from "@tanstack/react-router";

const ButtonLinkIssueExample = () => (
    <Button
        component={Link}
        params={{ topicId: "123" }}
        search={{ tab: 0 }}
        state
        to={"/topic/$topicId"}
    >
        {"View Topic Overview"}
    </Button>
);
```

```
TS2769: No overload matches this call.
  Overload 3 of 3, '(props: DefaultComponentProps<ExtendButtonBaseTypeMap<ButtonTypeMap<{}, "button">>>): Element | null', gave the following error.
    Type '{ children: string; component: LinkComponent<"a">; params: { topicId: string; }; search: { tab: 0; }; state: true; to: string; }' is not assignable to type 'IntrinsicAttributes & ButtonOwnProps & Omit<ButtonBaseOwnProps, "classes"> & CommonProps & Omit<...>'.
      Property 'component' does not exist on type 'IntrinsicAttributes & ButtonOwnProps & Omit<ButtonBaseOwnProps, "classes"> & CommonProps & Omit<...>'.
```

Just to clarify this was not an issue prior to the 1.56.1 update

**Comment by schiller-manuel** [comment] 2024-09-07 13:23
@christopherschroer please provide a minimal complete example, e.g. by forking one of the existing router examples on stackblitz

**Comment by felix-bohlin** [comment] 2024-09-09 07:33
Upgrading to 1.56.5 solved this issue for me. 👍

**Comment by ruiaraujo012** [comment] 2024-09-09 08:57
> Yeah was about to say that that, not only the route types broke but apparently search also broke, even after the changes suggested by [@chorobin](https://github.com/chorobin)
> 
> ```
> Type '{ search: string | undefined; action?: string | undefined; redirect?: string | undefined; }' is not assignable to type 'never'.
> 
> 47    search: (old) => ({
> ```

Same here, but if I put `from` and/or `to` the error goes away.

**Comment by ruiaraujo012** [comment] 2024-09-09 09:46
@schiller-manuel [Here](https://stackblitz.com/edit/tanstack-router-padurs?file=src%2Froutes%2Ftabs.tsx) is a reproduction of the `search`

**Comment by levrik** [comment] 2024-09-09 11:12
I wanted to upgrade to latest version from 1.46.7 but also had to stop at 1.53.1 as 1.56.1 is completely broken on the type-level. I'm using a custom `createLink` helper (need to map a few things that the built-in does not) and basically `to` is simply `any`, it complains about `search` being required, `params` is also simply `any`.

**Comment by borstessi** [comment] 2024-09-09 11:21
Having type issues after updating as well.

**Comment by mathewcst** [comment] 2024-09-09 11:38
I think we can close this issue now since v1.56.5 fixed types (at least for me)

**Comment by chorobin** [comment] 2024-09-09 11:47
> I wanted to upgrade to latest version from 1.46.7 but also had to stop at 1.53.1 as 1.56.1 is completely broken on the type-level. I'm using a custom `createLink` helper (need to map a few things that the built-in does not) and basically `to` is simply `any`, it complains about `search` being required, `params` is also simply `any`.

Can you provide a reproduction of your use case. `createLink` should still work so there might be something else here causing it

**Comment by borstessi** [comment] 2024-09-09 12:06
Issue even with new version: "@tanstack/react-router": "^1.56.5",

```
TS2322: Type "/ me" is not assignable to type "." | ".." | undefined
link. d. ts(44, 5): The expected type comes from property to which is declared here on type
NavigateOptions<unknown, string, "/ me", string, "">
```

```
TS2353: Object literal may only specify known properties, and s does not exist in type
ParamsReducerFn<unknown, "SEARCH", string, string | undefined>
link. d. ts(61, 5): The expected type comes from property search which is declared here on type
NavigateOptions<unknown, string, string | undefined, string, "">
```

**Comment by chorobin** [comment] 2024-09-09 12:15
> Issue even with new version: "@tanstack/react-router": "^1.56.5",
> 
> ```
>  <Menu.Item
>       data-testid={"dropdown-menu-item-2"}
>       key={"dropdown-menu-item-2"}
>       onClick={() => navigate({ to: "/me" })}
>       leftSection={
>         <User style={{ width: rem(14), height: rem(14) }} weight="bold" />
>       }
>     >
>       {t("common.profile.one")}
>     </Menu.Item>
> ```
> 
> ```
> TS2322: Type "/ me" is not assignable to type "." | ".." | undefined
> link. d. ts(44, 5): The expected type comes from property to which is declared here on type
> NavigateOptions<unknown, string, "/ me", string, "">
> ```
> 
> ```
> navigate({
>                 search: {
>                   s: firstIncompleteStep.id,
>                 },
>                 replace: true,
>               });
> ```
> 
> ```
> TS2353: Object literal may only specify known properties, and s does not exist in type
> ParamsReducerFn<unknown, "SEARCH", string, string | undefined>
> link. d. ts(61, 5): The expected type comes from property search which is declared here on type
> NavigateOptions<unknown, string, string | undefined, string, "">
> ```
> 
> after the upgrade i have 55 errors in 32 files - all complaining about navigate and link issues with the to or search property.

Looks like your `router` type is being inferred as `unknown`.

Make sure router dependencies are up to date. Can you delete `node_modules`, reinstall and regenerate your route tree. If the issue still persists,  check the type of `router`. check if there are any type errors in `routeTree.gen.ts`. type checking is turned off automatically for this file, but it can be helpful to see if there are any type errors causing problems.

A minimal reproduction from one of our examples can help us figure out the issue

**Comment by borstessi** [comment] 2024-09-09 12:26
@chorobin you were right. I forgot that i set the router type manually, which was somehow wrong now. As i changed it now it's working as expected. thanks!

**Comment by felix-bohlin** [comment] 2024-09-09 12:50
If anyone's using Vite, this solved it for me. I can use the latest `@tanstack/react-router version` now.

vite.config.ts
```diff
- import { TanStackRouterVite } from "@tanstack/router-vite-plugin"
+ import { TanStackRouterVite } from "@tanstack/router-plugin/vite"
```

**Comment by christopherschroer** [comment] 2024-09-09 14:00
> [@christopherschroer](https://github.com/christopherschroer) please provide a minimal complete example, e.g. by forking one of the existing router examples on stackblitz

@chorobin Here is minimal reproduction using basic start example

https://stackblitz.com/edit/tanstack-router-4ptxpj?file=app%2Fcomponents%2FDefaultCatchBoundary.tsx

I edited `DefaultCatchBoundary.tsx` to use Material UI `Button` components and passed the TanStack Router `Link` component to the `Button` `component` prop. I also passed a value to the `search` prop of the `Button` in the `else` branch (after adding a `validateSearch` function to the index `Route`). This way, you can see that `Button` with the `Link` component passed to the `component` prop works as long as you are not using the `search` prop

**Comment by kisonay** [comment] 2024-09-09 19:35
The root cause of my issue was how I was defining the router:

```
const router: any = createRouter({
  routeTree,
  context: {
    user: null,
  },
  defaultErrorComponent: ErrorMessage,
  defaultNotFoundComponent: NotFoundMessage,
});
```

The thing that was messing everything up was the `:any` not sure why it worked up until the most recent update.

**Comment by chorobin** [comment] 2024-09-09 22:09
> > [@christopherschroer](https://github.com/christopherschroer) please provide a minimal complete example, e.g. by forking one of the existing router examples on stackblitz
> 
> [@chorobin](https://github.com/chorobin) Here is minimal reproduction using basic start example
> 
> https://stackblitz.com/edit/tanstack-router-4ptxpj?file=app%2Fcomponents%2FDefaultCatchBoundary.tsx
> 
> I edited `DefaultCatchBoundary.tsx` to use Material UI `Button` components and passed the TanStack Router `Link` component to the `Button` `component` prop. I also passed a value to the `search` prop of the `Button` in the `else` branch (after adding a `validateSearch` function to the index `Route`). This way, you can see that `Button` with the `Link` component passed to the `component` prop works as long as you are not using the `search` prop

Yes, so before we allowed a `Link` without a `to` or ` from` to resolve to all routes which causes problems due to a lack of type safety and eventually editor performance issues when apps get larger. We want to encourage people to use `to` or `from`. The problem here is that `Link` is a component with type parameters, so if you pass it directly as a `component` prop then MUI will actually just use the default type argument  because there is no inference site for `Button`.

You can fix this by wrapping `Link` with explicit props which would give you proper type safety https://stackblitz.com/edit/tanstack-router-rsgndz?file=app%2Fcomponents%2FDefaultCatchBoundary.tsx

**Comment by kisonay** [comment] 2024-09-09 22:32
The root cause of my issue was how I was defining the router:

```
const router: any = createRouter({
  routeTree,
  context: {
    user: null,
  },
  defaultErrorComponent: ErrorMessage,
  defaultNotFoundComponent: NotFoundMessage,
});
```

The thing that was messing everything up was the `: any` not sure why it worked up until the most recent update.

**Comment by levrik** [comment] 2024-09-10 06:58
I'm facing the issue that with 1.56.1 (up to 1.56.5) `search` suddenly became required, even when `to` is not given.
It doesn't matter if using file-based routing or code-based one.

**Comment by felix-bohlin** [comment] 2024-09-11 08:46
Is this a Material UI v6 issue?
Here's a repro with the issues I'm having:
https://stackblitz.com/github/tanstack/router/tree/main/examples/react/basic-react-query-file-based?embed=1&theme=dark&preset=node&file=src/main.tsx

**Comment by felix-bohlin** [comment] 2024-09-11 09:01
Here's a repro with the issues I'm having: https://stackblitz.com/edit/tanstack-router-4eu4m2?file=src%2Froutes%2F__root.tsx&preset=node

I'm also getting some issues in regards with useNavigate and the search option but I'm struggling to reproduce that, although it all started erroring at the same time.

**Comment by chorobin** [comment] 2024-09-11 20:35
> Here's a repro with the issues I'm having: https://stackblitz.com/edit/tanstack-router-4eu4m2?file=src%2Froutes%2F__root.tsx&preset=node
> 
> I'm also getting some issues in regards with useNavigate and the search option but I'm struggling to reproduce that, although it all started erroring at the same time as I got the issue above.

Before this change, it would resolve to all routes in the route tree which wasn't type safe, now it type errors. This is because `Link` is a component with type parameters and a MUI button does not take the same type parameters and therefore it was impossible for it to narrow to the correct type. In most cases you want the narrowing to a particular route because you lose type safety.

https://stackblitz.com/edit/tanstack-router-66nose?file=src%2Froutes%2F__root.tsx

**Comment by jvllmr** [comment] 2024-09-12 07:37
> > Here's a repro with the issues I'm having: https://stackblitz.com/edit/tanstack-router-4eu4m2?file=src%2Froutes%2F__root.tsx&preset=node
> > I'm also getting some issues in regards with useNavigate and the search option but I'm struggling to reproduce that, although it all started erroring at the same time as I got the issue above.
> 
> Before this change, it would resolve to all routes in the route tree which wasn't type safe, now it type errors. This is because `Link` is a component with type parameters and a MUI button does not take the same type parameters and therefore it was impossible for it to narrow to the correct type (before it just resolved to all routes). In most cases you want the narrowing to a particular route because you get better type safety.
> 
> https://stackblitz.com/edit/tanstack-router-66nose?file=src%2Froutes%2F__root.tsx

This might be a workaround, but I think this can get really messy within larger code-bases. Short: It is not as elegant as the previous solution.

I don't know if it was mentioned here already: I face the same issue with search props when creating Link components via `createLink`.

**Comment by felix-bohlin** [comment] 2024-09-12 08:19
> Before this change, it would resolve to all routes in the route tree which wasn't type safe, now it type errors. This is because `Link` is a component with type parameters and a MUI button does not take the same type parameters and therefore it was impossible for it to narrow to the correct type (before it just resolved to all routes). In most cases you want the narrowing to a particular route because you get better type safety.
> 
> https://stackblitz.com/edit/tanstack-router-66nose?file=src%2Froutes%2F__root.tsx

Thanks for you reply chorobin!

Should this be raised with the MUI team? While it could solve that issue, wrapping the `Link` component everywhere we use it in the codebase results in messy/confusing boilerplate. The code still works so I assume most people in a similar situation will just put a `@ts-ignore` anywhere that error pops up and move on, which is even less ideal.

**Comment by chorobin** [comment] 2024-09-12 15:07
After some thought I think `createLink` is ideal for this. It keeps the narrowing you'd otherwise have with `Link` which is more type safe

https://stackblitz.com/edit/tanstack-router-bict11?file=src%2Froutes%2F__root.tsx

Thanks for the understanding. We want to solve these problems avoiding TS performance footguns

**Comment by jvllmr** [comment] 2024-09-12 15:14
> > Before this change, it would resolve to all routes in the route tree which wasn't type safe, now it type errors. This is because `Link` is a component with type parameters and a MUI button does not take the same type parameters and therefore it was impossible for it to narrow to the correct type (before it just resolved to all routes). In most cases you want the narrowing to a particular route because you get better type safety.
> > https://stackblitz.com/edit/tanstack-router-66nose?file=src%2Froutes%2F__root.tsx
> 
> Thanks for you reply chorobin!
> 
> Should this be raised with the MUI team? While your example could solve that issue, wrapping the `Link` component like that everywhere we use it in the codebase results in messy/confusing boilerplate. The code still works so I assume most people in a similar situation will just put a `@ts-ignore` anywhere that error pops up and move on, which is even less ideal.

The best solution for usage with polymorphic components is using the undocumented `createLink` function:



```typescript
import {ActionIcon, ActionIconProps} from "@mantine/core";
import { createLink } from "@tanstack/react-router";


export const ActionIconLink = createLink(
  (props: Omit<ActionIconProps, "component"> & { title?: string }) => (
    <ActionIcon component="a" {...props} />
  ),
);

```

Then one can use ActionIconLink anywhere in the codebase. Only drawback is that `createLink` is an undocumented function and might be subject to change.

**Comment by schiller-manuel** [comment] 2024-09-12 15:45
@ruiaraujo012 in such cases you need to set `to='.'`
I updated the docs accordingly: https://tanstack.com/router/latest/docs/framework/react/guide/search-params#writing-search-params

**Comment by schiller-manuel** [comment] 2024-09-14 08:52
closing this now as the typing issues seem to be resolved.
if you still encounter problems, please create a new github issue including a minimal complete example.

**Closed by schiller-manuel** 2024-09-14 08:52 UTC

**Comment by AdrianLsk** [comment] 2024-09-30 15:20
I am facing this issue as well, any version above 1.53.1 starts showing type errors when using useNavigate, for example with

`
navigate({
	to: "/workspaces/$workspaceId/welcome",
	params: { workspaceId: setupResponse.workspaceId },
});
`

I get type error that workspaceId in params doesnt exist because is never

**Comment by borstessi** [comment] 2024-09-30 15:44
i fixed there erros by using from property with the useNavigate hook:

`const navigate = useNavigate({ from: "/admin/users" });`

i mostly used it when there are search params. Maybe it helps with your case too.
