### ISSUE TITLE
`location` and `context` not present in `loaderDeps` method options

### ISSUE THREAD

**Issue by waweber** [TanStack/router#2081] opened 2024-08-03 20:23 UTC
### Describe the bug

The docs show that `search`, `context`, and `location` are provided via the `opts` argument of the `loaderDeps` method. (https://tanstack.com/router/latest/docs/framework/react/api/router/RouteOptionsType#loaderdeps-method)

However, only `search` seems to be present. #1216 also reports that the `context` property is missing.

### Your Example Website or App

https://stackblitz.com/edit/github-etvuuc?file=src%2Fmain.tsx%3AL35

### Steps to Reproduce the Bug or Issue

See that the only property on `opts` is `search`.

### Expected behavior

All the properties listed in the docs should be present. Specifically, I need the route to reload its data if a value in the url's hash changes.

### Platform

Tanstack router package version 1.46.4

**Comment by SeanCassiere** [comment] 2024-08-05 23:33
Duplicate of #1216

**Closed by SeanCassiere** 2024-08-05 23:33 UTC
