### ISSUE TITLE
Issue while using useBlocker hook

### ISSUE THREAD

**Issue by rahulretnan** [TanStack/router#1193] opened 2024-02-17 14:10 UTC
### Describe the bug

There is an issue while using Use Blocker Hook with custom confirm dialog. The browser seem to be shaking.

This is the current source code for the` useBlocker` hook 
```tsx
export function useBlocker(
  blockerFn: BlockerFn,
  condition: boolean | any = true,
): void {
  const { history } = useRouter()

  React.useEffect(() => {
    if (!condition) return
    return history.block(blockerFn)
  })
}
```
 Here the `useEffect` is triggered on every render and that might be causing the issue
 

### Your Example Website or App

https://stackblitz.com/edit/github-ejinve?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

1. Click on `About`
2. Then try going back to `Home`
3. Click `Cancel` on confirm model
4. Then Click on reload button
5. The browser will start to shake

### Expected behavior

As a user, when I try to change my route or reload on a page where `useBlocker` hook is used. I should be prompted with a Confirm dialog. There shouldn't be any browser window shaking

### Screenshots or Videos

https://github.com/TanStack/router/assets/33414802/6b43410f-2448-4cb1-9ab8-1061bd1e5540

### Platform

- OS: Linux
- Browser: Chrome
- Version: 121.0.6167.184

**Comment by SeanCassiere** [comment] 2024-02-29 01:50
This is a glitch with Stackblitz and its preview window.
This glitching-out behaviour does not exist on local and production deployments.

**Comment by rahulretnan** [comment] 2024-03-07 15:17
I experienced the same in the local only, please follow the same steps to reproduce.

**Comment by SeanCassiere** [comment] 2024-03-08 01:05
> I experienced the same in the local only, please follow the same steps to reproduce.

Tested locally on the latest version `1.19.1` and the issue stated in the OP of the screen/browser shaking does not occur. See the screen capture below.

Although, the screen capture was done in Arc, I followed this up with tests in Chrome, Firefox, and Safari to confirm the same result.

https://github.com/TanStack/router/assets/33615041/4a959824-0304-4b58-a31f-a128a803a0cb

**Comment by rahulretnan** [comment] 2024-03-08 19:24
Thank you @SeanCassiere for taking time to test this issue and help me resolve them. The test you shared in the video works for me as well. But the issue occurs only when I try going back and click on cancel and then try to reload the browser as I shared in my video. I know this is really an edge case, would appreciate a fix for it.

Also I'm yet to test this with the latest version, I'll update here if it gets resolved in the new version.

**Comment by SeanCassiere** [comment] 2024-03-09 03:40
@rahulretnan I tried this again following these steps that I extracted from your original video (with the exception that I'm using the latest version of the router packages).

1. Run the example on my machine on the latest version `1.19.2` version of the router packages.
2. Open the app on the browser (home page).
3. Click on the link to the *about* page.
4. Click on the link to the *home* page.
5. window.confirm is shown to confirm me wanting to switch pages.
6. Click on the "cancel" button.
7. Reload the page (click on the *reload* button since the blocker is still active).
8. Click on the link to the *home* page.
9. window.confirm is shown to confirm me wanting to switch pages.
10. Click on the "cancel" button.
11. Click on the link to the *home* page.
12. window.confirm is shown to confirm me wanting to switch pages. 
13. Click on the "ok" button.

At no point did I observe any screen flicker.

https://github.com/TanStack/router/assets/33615041/5b6be708-0fb2-4dc8-942c-a4b9355d1000

**Comment by SeanCassiere** [comment] 2024-04-01 02:56
🔴 Closing this, since we were unable to reproduce the unexpected behaviour described in issue.

If anyone can reliably reproduce this, please request for this issue to re-opened. Just keep in mind that the bug should be reproducible outside of the embedded Stackblitz iframe, and in a new tab as that is most representative of *real world* usage.

PS: Also, keep in mind if you are using `window.confirm` as your callback, you also are contending with whatever minute differences there are in the implementation of the function on different platforms and browsers.

**Closed by SeanCassiere** 2024-04-01 02:56 UTC
