### ISSUE TITLE
`Uncaught (in promise)` error when using `redirect` in `beforeLoad`

### ISSUE THREAD

**Issue by hrasoa** [TanStack/router#1499] opened 2024-04-20 10:28 UTC
### Describe the bug

I have a `Uncaught (in promise)` error when I use `redirect` in `beforeLoad`. 

It was working fine with `@tanstack/react-router` `1.28.1`, the bug happens since `1.28.3`

### Your Example Website or App

https://tanstackrouterzes8cv-3goq--3001--7dbe22a9.local-credentialless.webcontainer.io/

### Steps to Reproduce the Bug or Issue

Load the `index` route: https://tanstackrouterzes8cv-3goq--3001--7dbe22a9.local-credentialless.webcontainer.io/
There is an error in the console:  `Uncaught (in promise)`

### Expected behavior

It should redirect to the `/posts/` page.

### Platform

- OS: macOS Sonoma 14.4.1
- Browser:Chrome Version 123.0.6312.124

### Additional context

Project: https://stackblitz.com/edit/tanstack-router-zes8cv

I have to use the pattern `return new Promise()` as I'm using `relay` to load some data:

```ts
  beforeLoad({ context: { environment } }) {
    if (environment) {
      return new Promise((_, reject) => {
        const { unsubscribe } = fetchQuery<MainQuery>(
          environment,
          node,
          {}
        ).subscribe({
          next(data) {
            const view = data.bookmarkViews.edges[0]?.node;
            if (view) {
              unsubscribe();
              reject(
                redirect({
                  to: '/bookmark-view/$view-id',
                  params: { 'view-id': view.id },
                  replace: true,
                })
              );
            }
          },
        });
      });
    }
    return Promise.resolve();
  },
```

**Comment by SeanCassiere** [comment] 2024-04-20 11:51
Duplicate of #1480, closing this issue and tracking this bug in the mentioned thread.

**Closed by SeanCassiere** 2024-04-20 11:51 UTC
Labels: bug
