### ISSUE TITLE
defaultPendingMinMs blocks the page on load

### ISSUE THREAD

**Issue by TkDodo** [TanStack/router#1646] opened 2024-05-21 09:17 UTC
### Describe the bug

when hard-loading a page for the first time, it will show the loader (or an empty page) for the `pendingMinMs` time even if the route has no loader at all or the loader resolves before `pendingMs` has expired (default 1 second).

This is _not_ the case when navigating to a route

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-hzdror?file=src%2Fmain.tsx&preset=node

### Steps to Reproduce the Bug or Issue

- reload the sandbox on the `Home` tab (this route has no loader)
- you should see an empty page for 5 seconds.
  - if you comment in the `defaultPendingComponent`, you should see `loading...` for 5 seconds.
- now go to the `about` tab (which has a 500ms loader, so shorter than the default 1s `pendingMs`) and reload it.
  - you should, again see the `loading...` (or an empty screen) for 5 seconds
- now navigate to `Home` via the link
  - home loads instantly, as expected, because it has no loader.

### Expected behavior

I'd expect `pendingMinMs` to not influence the hard reload times, just like it doesn't block navigations either.

### Platform

any

### Additional context

This behaviour is observable even with the default settings, but because `defaultPendingMinMs` is "just" 500ms, it's harder to spot.

**Comment by acoBOYZ** [comment] 2024-05-23 12:30
Yes I have the same issue.

**Comment by shevdrakon** [comment] 2024-05-24 21:11
In addition I can see that `pendingMs` is ignoring. `Loading...` will be displayed in 1s (default value) even if value was changed to smth big, i.e. `10_000`. 

> By default, TanStack Router will show a pending component for loaders that take longer than 1 second to resolve. This is an optimistic threshold that can be configured via: `pendingMs`

I would expect not to see `Loading...` for 10s if loader still not resolved.

**Comment by ericchernuka** [comment] 2024-07-06 16:32
This is an interesting one. I haven't dug in, but I just discovered this today also.

**Comment by schiller-manuel** [comment] 2024-07-16 17:00
this will be fixed by #1907 

reproducer with pre-release package: https://stackblitz.com/edit/tanstack-router-um44ng?file=src%2Fmain.tsx&preset=node

**Closed** 2024-07-16 17:34 UTC

**Comment by jjonesrs** [comment] 2024-08-14 06:24
@schiller-manuel I've forked the reproducer and compared version 1.45.2 with versions 1.45.3 through 1.47.5 (which includes PR #1907). You can find the comparison here: https://stackblitz.com/edit/tanstack-router-hsmnzk?file=src%2Fmain.tsx&preset=node

#### Observations

Version 1.45.2:

- The pending component appears on hard load for the entire layout, as documented in the original issue.

Versions 1.45.3 - 1.47.5:

- The pending component no longer appears on hard load for the layout.
- However, it still shows on hard load for the about component itself, i.e. under the nav.

#### Test Configuration

To make the behavior more noticeable, I made the following adjustments:

- Set `defaultPendingMs` to 5000ms
- Left the loader delay at 500ms

#### Expected Behavior

Based on this configuration, we should expect:

- The pending component should only show if the pending state lasts for at least 5000ms.

#### Questions

- Is this the intended behavior for versions 1.45.3 and above?
- Should the pending component still appear on hard load for the about component, given the `defaultPendingMs` setting?
