### ISSUE TITLE
Upgrade from 1.39.4 to 1.45.4 causes lockup on special charactors in URLs

### ISSUE THREAD

**Issue by matclayton** [TanStack/router#1980] opened 2024-07-18 11:19 UTC
### Describe the bug

When opening a page direct, not via a link. we are observing pages locking up, and taking 100% cpu. 

I suspect this is due to the change in 1.45.2 which mentions encoding, we'll try and bisect it now to get a more accurate picture. When the bug occurs it essentially crashes chrome, and is reliably reproduced but only on a quick connection.

### Your Example Website or App

https://www.mixcloud.com/3%CE%9A%CE%91%CE%A0%CE%A0%CE%91/

### Steps to Reproduce the Bug or Issue

Goto the url direct, not via a link, (it is using preload), page locks up

### Expected behavior

Not hit 100% and Chrome crash

### Platform

macOS, Chrome, 126.0.6478.128

**Comment by schiller-manuel** [comment] 2024-07-18 17:24
Can you please provide a minimal complete example by forking one of the examples on stackblitz?
e.g. https://tanstack.com/router/v1/docs/framework/react/examples/basic-file-based

**Comment by SeanCassiere** [comment] 2024-07-26 01:54
Closing this since a reproduction wasn't provided.

**Comment by matclayton** [comment] 2024-07-30 23:26
@SeanCassiere a colleague had more time to make a repro case. See https://github.com/TanStack/router/issues/2053 it’s really reproducible under some specific circumstances.

**Comment by SeanCassiere** [comment] 2024-07-31 00:02
@matclayton thank you, will track the progress of this bug in the mentioned issue.

**Closed by SeanCassiere** 2024-07-31 00:02 UTC
Labels: information needed
