### ISSUE TITLE
Hovering over a link in a NotFoundComponent with preloadintent and no staletime

### ISSUE THREAD

**Issue by jmdeschenes** [TanStack/router#1220] opened 2024-02-24 15:07 UTC
### Describe the bug

When in a notFoundComponent, a `<Link to='...'>` will automatically load the page. Interestingly, if you use a button with a onClick: `() => navigate('/')`... Nothing happens

### Your Example Website or App

https://stackblitz.com/edit/github-h4dx75?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

1. Clink on the `Invalid Link` Button or enter an invalid link in the URL.  
2. Hover over the go back button
3. The screen goes blank

If you comment either:
1.   `defaultPreload: 'intent'` or `defaultPreloadStaleTime: 0`, it works as expected. As a workaround you can set the link: `<Link to='/' preload={false}>...</Link>` and it should work as expected.

### Expected behavior

As a user, I would expect that I can navigate when I click on a link.

### Platform

- OS: Linux
- Browser: Chrome
- Version: 121.0.6167.160

**Comment by tannerlinsley** [comment] 2024-02-24 15:37
I’m working on this issue right now.

**Comment by pontusdacke** [comment] 2024-03-13 09:35
I believe this is related to/a dupe of [1201](https://github.com/TanStack/router/issues/1201). Any progress on your work, @tannerlinsley ?

**Comment by schiller-manuel** [comment] 2024-03-27 17:28
should be fixed, please open a new issue if this is still relevant

**Closed by schiller-manuel** 2024-03-27 17:28 UTC
