### ISSUE TITLE
Default search params from validateSearch do not populate the URL

### ISSUE THREAD

**Issue by efie45** [TanStack/router#1184] opened 2024-02-14 14:34 UTC
### Describe the bug

When using `validateSearch`, if you return a default value it becomes available via the `useSearch` hook in a component, but it does not appear in the URL. 

### Your Example Website or App

https://stackblitz.com/edit/github-cqxxd6?file=src%2Froutes%2Fabout.tsx

### Steps to Reproduce the Bug or Issue

1. Click on the 'about' link

### Expected behavior

The default parameter from validateSearch is available via `useSearch` but does not show in the URL search params. 

### Platform

- OS: Windows
- Browser: Chrome, Edge

**Comment by ruiaraujo012** [comment] 2024-04-12 09:38
Same thing here, any update on this?
I'm having a strange behavior where my `validateSearch` run link 20 times or more when I navigate to the route (and run about 4 times in other routes)

**Comment by amjed-ali-k** [comment] 2024-05-08 12:47
> ### Your Example Website or App
> [stackblitz.com/edit/github-cqxxd6?file=src%2Froutes%2Fabout.tsx](https://stackblitz.com/edit/github-cqxxd6?file=src%2Froutes%2Fabout.tsx)
> 


This link is invalid

**Comment by a1eksandrk** [comment] 2024-05-15 08:39
Raising the question. I also encountered this problem when using `useNavigate`, during validation the default parameters are returned, but they are not substituted in the `URL`.

**Comment by collinosh** [comment] 2024-05-17 23:16
This is our biggest migration hurdle so far.  Our users often share links to daily reports/metrics which aren't always opened the same day by the recipient- because the default state is omitted from the URL, there's no way to guarantee state consistency without forcing a redirect to update the search.

Would love to hear if anyone has a better solution, love the type safety of this library but I'm finding myself sinking far too many hours trying to reinvent the wheel.

**Comment by PrimaMateria** [comment] 2024-06-04 14:44
I have made the following workaround until it gets fixed. Not nice, but it doesn't leave the URL without the search parameters.

```
  const navigate = useNavigate();
  useEffect(() => {
    const parameters = new URLSearchParams(document.location.search);
    if (parameters.size === 0) {
      void navigate({ search: defaultSearchParameters, replace: true });
    }
  }, [navigate]);
```

**Comment by bhaugeea** [comment] 2024-07-09 18:02
This seems at least partly related to a new issue I just posted: #1928. Currently it appears that a full page load does populate these values but a router nav doesn't. Meanwhile the full load has other problems but the router nav works fine.

**Comment by schiller-manuel** [comment] 2024-07-09 18:51
@efie45  can you please provide the reproducer again?
this might be fixed by #1907

**Comment by levrik** [comment] 2024-07-24 12:47
This works for me and I would actually like the exact opposite of not having default search params being set in the URL. Was surprised to find an issue complaining about the opposite.

**Comment by lukaskoeller** [comment] 2024-07-26 05:13
@schiller-manuel Following up on the already existing discord discussion, I'll link my reproducer again here for completeness: https://github.com/lukaskoeller/tanstack-react-router-useEffect-navigate-reproduction?tab=readme-ov-file#reproduction-2 using `v1.45.8`



> This seems at least partly related to a new issue I just posted: #1928. Currently it appears that a full page load does populate these values but a router nav doesn't. Meanwhile the full load has other problems but the router nav works fine.

This is basically the exact behavior I experience as well

**Comment by lukaskoeller** [comment] 2024-07-26 05:30
Another related issue I noticed, is that the [`<Link>` throws a typescript error](https://github.com/lukaskoeller/tanstack-react-router-useEffect-navigate-reproduction/blob/f57b62c9e3da0bb189dadf54f9319df1119ba3b2/src/App.tsx#L23), that
> Property 'search' is missing

although all search params [use `optional`](https://github.com/lukaskoeller/tanstack-react-router-useEffect-navigate-reproduction/blob/f57b62c9e3da0bb189dadf54f9319df1119ba3b2/src/router.ts#L45) from zod:

```tsx
export const repro3Route = createRoute({
  getParentRoute: () => rootRoute,
  path: "/repro3",
  validateSearch: object({
    param1: number().optional().default(7),
    param2: string().optional().default("defaultValue1"),
  }),
  component: Repro3,
});
```

**Comment by reihwald** [comment] 2024-09-11 20:58
This issue still happens for me. The different behaviour is strange. @schiller-manuel Have you maybe had the chance to look into this further?

I found something else that I find strange.

Shouldn't `const search = useSearch({ from: null! })` and `const searchFromLocation = useLocation({ select: (l) => l.search }) ` always return the same thing?

`searchFromLocation` seems to mirror what is seen in the url and `search` seems to always show the correct fallbacks.
Here is is quick reproduction stackblitz: https://stackblitz.com/edit/github-2gwkq9?file=src%2Froutes%2Fparams.tsx

**Closed** 2024-10-12 16:12 UTC

**Comment by MariuzM** [comment] 2024-11-01 09:55
Hm I'm still having this issue and having with nav, what I'm missing? 
![Image](https://github.com/user-attachments/assets/c4a9cb14-3acc-44ef-92b7-bf3d2d439ca2)

**Comment by schiller-manuel** [comment] 2024-11-01 10:03
@MariuzM you need to tag the input type with `SearchSchemaInput`

see https://tanstack.com/router/latest/docs/framework/react/api/router/RouteOptionsType#validatesearch-method

or use one of the search schema validators listed here

https://tanstack.com/router/latest/docs/framework/react/guide/search-params#adapters

**Comment by allan-cannon** [comment] 2024-11-06 23:14
I'm still running into this issue on 1.78.2. Navigating to the route via url correctly applies the default search param but navigating using useNavigate fails to apply the default search param in the url even though it correctly passes the value to the component.

Here's my route: 

```
import { createFileRoute } from '@tanstack/react-router';
import { zodSearchValidator } from '@tanstack/router-zod-adapter';
import { z } from 'zod';
import { RegistrationDetailsPage } from '@/Registrations/V4/RegistrationDetailsPage';

export const RegistrationTabs = z.enum(['summary', 'rules', 'documents']);

export const Route = createFileRoute('/_authenticated/_app/registrations_/$id')({
  params: zodSearchValidator(z.object({ id: z.coerce.number().int().min(1) })),
  validateSearch: zodSearchValidator(
    z.object({
      tab: RegistrationTabs.default('documents'),
    }),
  ),
  component: RegistrationDetailsRoute,
});

function RegistrationDetailsRoute() {
  const { id } = Route.useParams();
  const { tab } = Route.useSearch();
  return (
    <RegistrationDetailsPage
      id={id}
      tab={tab}
    />
  );
}
```

Here's how I'm navigating:
  
```
navigate({
  to: '/registrations/$id',
  params: { id: registration.id },
})
```

Am I doing something wrong?

**Comment by schiller-manuel** [comment] 2024-11-07 01:02
@allan-cannon please create a new issue and include a complete minimal example
