### ISSUE TITLE
Unexpected trailing slash causes mismatch between exact link active option and url

### ISSUE THREAD

**Issue by seedy** [TanStack/router#1309] opened 2024-03-14 10:44 UTC
### Describe the bug

I have a route tree where a splat route handles redirecting to existing routes.
I have a route with an outlet and a child index route to display inside whenever the route is matched.

I have links with `activeOptions={{exact: true}}` to ensure they are active only when child routes are matched.

Whenever I refresh my page, `/about`, an unexpected trailing slash is added.

Because my Links have exact path matching, they don't match the same route if it has a trailing slash.

### Your Example Website or App

https://stackblitz.com/edit/github-m8im6s?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

1. Click on 'About' link => only this link is active
2. Click on 'About special' link => only this link is active
3. Click again on 'About' link
4. Refresh your browser, pressing CMD+R or F5
5. A trailing slash is added to your url => '/about/'

### Expected behavior

There should be no trailing slash added, as it is unexpected.

The link to "/about" is no longer active, because of the exact match pattern and trailing slash

### Screenshots or Videos

https://github.com/TanStack/router/assets/3367393/8173a84d-3d74-46d1-9998-6ea243091523

### Platform

- OS: macOS
- Browser: Chrome
- Version:  122.0.6261.112 (Official Build) (arm64)

**Comment by schiller-manuel** [comment] 2024-03-14 13:15
you are linking to the index page, so why don't you link to `/about/`?

**Comment by seedy** [comment] 2024-03-14 14:21
> you are linking to the index page, so why don't you link to `/about/`?

@schiller-manuel in a more complex context, with possibly redirections, it is not obvious that my link should hit `/about/`.

I am pointing at the inconsistent routing behavior : 
- I hit `/about` without refreshing
- I hit `/about/` once refreshed

**Comment by hansyulian** [comment] 2024-03-25 13:31
by the way, what is the cause of the trailing slash? i also hit the same problem

**Comment by SeanCassiere** [comment] 2024-03-27 06:32
This has been fixed with the [1.22.9](https://github.com/TanStack/router/releases/tag/v1.22.9) release.

**Closed by SeanCassiere** 2024-03-27 06:32 UTC

**Comment by jameslawson** [comment] 2024-04-14 09:13
I had a related issue and I was about to create another issue, but upgrading to [v1.27.0](https://github.com/TanStack/router/releases/tag/v1.27.0) fixed it for me. Now trailing slashes are always added and it seems exact matching works in even more cases (including another case I had). 🎉

**Comment by hansyulian** [comment] 2024-04-15 03:32
> I had a related issue and I was about to create another issue, but upgrading to [v1.27.0](https://github.com/TanStack/router/releases/tag/v1.27.0) fixed it for me. Now trailing slashes are always added and it seems exact matching works in even more cases (including another case I had). 🎉

yes i already fixed it in https://github.com/TanStack/router/pull/1372

**Comment by mudasirpandith** [comment] 2024-06-04 05:25
Is this fixed, I am having v1.28.1,  when deployed the url automatically redirects to `/` and gives 404 for that page and then shows the url with `/`? @hansyulian  @jameslawson

**Comment by SeanCassiere** [comment] 2024-06-04 05:59
> Is this fixed, I am having v1.28.1, when deployed the url automatically redirects to `*/` and gives 404 for that page and then shows the url without `/`? @hansyulian @jameslawson

I retested this and observed no issues.

@mudasirpandith retest your problem with the latest version.
If the issue still persists, open a new issue on Github with a minimal reproduction of the issue you are facing.
