### ISSUE TITLE
Nested layouts: Suggestions <Link to="?" /> returns the wrong "to" string

### ISSUE THREAD

**Issue by kcoet** [TanStack/router#890] opened 2023-12-28 12:03 UTC
### Describe the bug

I have a nested layout: `_layout._sidebar.questions.tsx`

When I create a link using component link, the suggested `to` attribute redirects us to the wrong page namely "/sidebar/questions"

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-8rwgeo?file=src%2Froutes%2F_layout._sidebar.index.tsx

### Steps to Reproduce the Bug or Issue

Create a flat route file structure like this: _layout._sidebar.questions.tsx , check the "to" attribute suggestion in the Link.

### Expected behavior

Currently pointing to `/sidebar/questions` it should be `/questions`

### Platform

- OS: Windows
- Browser: Chrome
- Version: 120.0.6099.130

**Comment by schiller-manuel** [comment] 2023-12-28 12:57
should be fixed by https://github.com/TanStack/router/pull/886

can you test?

**Comment by tannerlinsley** [comment] 2023-12-28 23:47
Can't reproduce any more

**Closed by tannerlinsley** 2023-12-28 23:47 UTC

**Comment by kcoet** [comment] 2023-12-29 02:09
I don't think this issue is fixed yet, still experiencing the same thing even after updating to v1.0.5

https://stackblitz.com/edit/tanstack-router-8rwgeo?file=src%2Froutes%2F_layout._sidebar.index.tsx

![image](https://github.com/TanStack/router/assets/110478020/5947ca04-6430-4a80-97fd-e8d7b4e889c6)

**Comment by schiller-manuel** [comment] 2024-01-07 02:08
same as https://github.com/TanStack/router/issues/899 ?
