### ISSUE TITLE
No type safety on useSearch({ strict: false })

### ISSUE THREAD

**Issue by RobertOstermann** [TanStack/router#1217] opened 2024-02-24 05:14 UTC
### Describe the bug

The type safety is not working as expected for `useSearch` or `useParams` when using `strict: false` in the options.

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-nan1d9?file=src%2Froutes%2Fdashboard.users.tsx

### Steps to Reproduce the Bug or Issue

1. Go to the Kitchen Sink File Base Example (any example with search params would work)
2. Change the `route.useSearch` to `useSearch({ strict: false })`
3. Add a `useParams({ strict: false })`
4. The types are not showing for either function as expected

### Expected behavior

With `strict: false` the type safety should be loosened to show all available types.

### Screenshots or Videos

`useSearch({ strict: false })` no type safety

![image](https://github.com/TanStack/router/assets/46828475/8038e518-97ea-47b6-8632-3b2a9f4476cc)

`useSearch({ strict: false, experimental_returnIntersection: true }) does not work. This does fix the same issue I see with `useParams` though.

![image](https://github.com/TanStack/router/assets/46828475/01b113a0-d60d-4a4f-9d62-c1115ff5c5dd)

`useParams({ strict: false })` no type safety

![image](https://github.com/TanStack/router/assets/46828475/65b8d903-df7b-48b7-ad60-d072fc2a03c0)

`useParams({ strict: false, experimental_returnIntersection: true })` fixes the issue for `useParams`

![image](https://github.com/TanStack/router/assets/46828475/991d251d-452a-451c-9e61-fff1aef4fc66)

### Platform

tanstack router version: 1.16.6
typescript: 5.3.3 (on my local, not sure what stackblitz is on)

**Comment by schiller-manuel** [comment] 2024-02-25 20:49
> `useParams({ strict: false })` no type safety

This is incorrect, this is type safe. You get back the **union** of all possible search parameters.

see https://stackblitz.com/edit/tanstack-router-kws5zj?file=src%2Froutes%2Fdashboard.users.tsx

```tsx
const search: {} | {} | {} | {
    showNotes?: boolean | undefined;
    notes?: string | undefined;
} | {
    usersView?: {
        sortBy?: "id" | "name" | "email" | undefined;
        filterBy?: string | undefined;
    } | undefined;
} | {
    ...;
} | {
    ...;
} | {
    ...;
}
```

> `useSearch({ strict: false, experimental_returnIntersection: true })` does not work.

Indeed, on stackblitz it does not work.
In VS Code it works as expected, so please try in a proper IDE:

![Screenshot 2024-02-25 at 21 49 24](https://github.com/TanStack/router/assets/6340397/5c25a7f1-52cb-4122-adab-2c43d791a5e0)

**Comment by RobertOstermann** [comment] 2024-02-25 21:35
@schiller-manuel I have tested in a "proper IDE". It was my thought that StackBlitz used VS Code on the web? So I figured providing StackBlitz examples would be easiest to reproduce. Here is what I am seeing on VS Code on my local machine...

`useParams({ strict: false })`: This does not work as I would expect in VS Code, or in StackBlitz. I would expect to get autocomplete when using this setup. It does return a union, as you have noted, but there is no autocomplete support and it views using any of the params as invalid.

![image](https://github.com/TanStack/router/assets/46828475/672b98d7-3837-4ab8-b014-bbd757160298)

`useParams({ strict: false, experimental_returnIntersection: true });`: Works as expected

![image](https://github.com/TanStack/router/assets/46828475/f08805e3-1e94-4a50-b48a-3eabe20f4361)

`useSearch({ strict: false })`: This does not work as I would expect in VS Code. It has the same behavior as `useParams({ strict: false })` and returns a union, but VS Code does not provider autocomplete support.

![image](https://github.com/TanStack/router/assets/46828475/13b24d35-0a30-46b3-a245-e52954f9ea73)

`useSearch({ strict: false, experimental_returnIntersection: true })`: This works as expected for a smaller amount of routes, but I get the `Type instantiation is excessively deep and possibly infinite` error on a project with ~30 routes, though only about 14 total search params. 

![image](https://github.com/TanStack/router/assets/46828475/8d6eac9e-532b-48c1-9e32-73d33096f366)

**Comment by schiller-manuel** [comment] 2024-02-25 21:45
> there is no autocomplete support

Since one of the union members is the empty object `{}`, TS cannot provide any autocomplete here if you don't narrow down the union since the union members don't have any properties in common (those would be the ones that could be autocompleted).

Can you please provide a reproducer where the `Type instantiation is excessively deep and possibly infinite` error occurs in a local VS Code instance?

**Comment by RobertOstermann** [comment] 2024-02-25 22:11
@schiller-manuel Ok, that makes sense, so only by using the `experimental_returnIntersection` will I get the autocomplete support I was expecting. Thank you for the quick reply.

I was able to reproduce the `Type instantiation` error, here is an example on CodeSandbox. I cloned the repo and tested on my local to ensure it was not just an issue on CodeSandbox.

[CodeSandbox](https://codesandbox.io/p/devbox/github/tanstack/router/tree/main/examples/react/kitchen-sink?embed=1&theme=dark&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cls6sla2n0007356m8oa0r0qp%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cls6sla2n0002356mb3qp8rtm%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cls6sla2n0004356mj7iy3dk4%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cls6sla2n0006356mrnmsaii2%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cls6sla2n0002356mb3qp8rtm%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls6sla2n0001356mbqqg65cq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cls6sla2n0002356mb3qp8rtm%2522%252C%2522activeTabId%2522%253A%2522cls6sla2n0001356mbqqg65cq%2522%257D%252C%2522cls6sla2n0006356mrnmsaii2%2522%253A%257B%2522id%2522%253A%2522cls6sla2n0006356mrnmsaii2%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls6sla2n0005356m3tpa8xr7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3001%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cls6sla2n0005356m3tpa8xr7%2522%257D%252C%2522cls6sla2n0004356mj7iy3dk4%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls6sla2n0003356mtmecylg9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522cls6sla2n0004356mj7iy3dk4%2522%252C%2522activeTabId%2522%253A%2522cls6sla2n0003356mtmecylg9%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by schiller-manuel** [comment] 2024-02-25 22:22
Did you maybe share the wrong link? there is no error on line 435

![Screenshot 2024-02-25 at 23 22 02](https://github.com/TanStack/router/assets/6340397/b55fba11-eff0-4f2d-8b81-c57c61fdf3ef)

**Comment by RobertOstermann** [comment] 2024-02-25 22:26
Oh my bad, forgot to fork it. Try this link

[CodeSandbox](https://codesandbox.io/p/devbox/crimson-fire-vr7gww?workspaceId=9610ac31-204f-4afb-b400-e3755ca4208e&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cls6sla2n0007356m8oa0r0qp%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cls6sla2n0002356mb3qp8rtm%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cls6sla2n0004356mj7iy3dk4%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cls6sla2n0006356mrnmsaii2%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cls6sla2n0002356mb3qp8rtm%2522%253A%257B%2522id%2522%253A%2522cls6sla2n0002356mb3qp8rtm%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522cls6sla2n0006356mrnmsaii2%2522%253A%257B%2522id%2522%253A%2522cls6sla2n0006356mrnmsaii2%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls6sla2n0005356m3tpa8xr7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3001%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cls6sla2n0005356m3tpa8xr7%2522%257D%252C%2522cls6sla2n0004356mj7iy3dk4%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls6sla2n0003356mtmecylg9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522cls6sla2n0004356mj7iy3dk4%2522%252C%2522activeTabId%2522%253A%2522cls6sla2n0003356mtmecylg9%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by schiller-manuel** [comment] 2024-02-25 22:45
thanks for the reproducer, the fix is released with https://github.com/TanStack/router/releases/tag/v1.17.4

**Comment by RobertOstermann** [comment] 2024-02-25 23:42
Hm yes, seems like it worked for my smaller example, but once I updated that to have a few more routes it unfortunately broke again.

**Comment by rajbirjohar** [comment] 2024-05-16 18:29
Do you know what could be some possible usecases where useSearch would return an empty object as a type? I too am facing this issue and from as far as I can tell when using zod schemas atleast, it will give me the correct union of all the types but adds on that empty object.

**Comment by schiller-manuel** [comment] 2024-05-16 18:46
you probably have at least one router without a `validateSearch` and thus the empty object will be put into the union

**Comment by rajbirjohar** [comment] 2024-05-16 18:56
@schiller-manuel Gotcha, yes I have multiple. Workaround? Should we add a validateSearch to all routes and somehow return undefined?

**Comment by schiller-manuel** [comment] 2024-05-16 19:05
why is having the empty object a problem?

**Comment by rajbirjohar** [comment] 2024-05-16 20:09
Because I am getting a type safety issue where the key does not exist within the empty object.

```ts
const { page } = useSearch({
    strict: false
  });
```
```ts
Property 'page' does not exist on type '{} | { redirect?: string | undefined; } | { sort?: string | undefined; search?: string | undefined; page?: number | undefined; limit?: number | undefined; } | { sort?: string | undefined; search?: string | undefined; page?: number | undefined; limit?: number | undefined; } | { ...; }'.
```

I have plenty of pages that are validating the search params including a `page` param but it still cannot detect it. Do I have to assert it as a certain shape because that would be sort of a pain to deal with.

The use case I have is a component that updates a single param in the url across multiple tables/pages.

**Comment by schiller-manuel** [comment] 2024-05-16 21:03
you also have a route with search `{ redirect?: string | undefined; }`, this also does not have the `page` property.
So the empty object is not the only one that prevents you from destructuring like you showed.
 
If `experimental_returnIntersection` does not work for you, you need to narrow down the union yourself, e.g. like this:

```tsx
const search = useSearch({
    strict: false
});
if ('page' in search) {
    console.log(page.search);
}
```

**Comment by rajbirjohar** [comment] 2024-05-16 21:19
Got it. `experimental_returnIntersection` does work. Any idea when it will no longer be experimental? Also, should probably be another discussion but how would you handle reading the search params and converting them to a url param string like below? This doesn't work since it expects all values to be strings meaning I would need to coerce all numbers and join all string arrays before performing this. Is there a utility function available that would do this? I'd like to essentially extract the search params from the url then send them to my API as search params.

```
const searchParams = routeApi.useSearch();

const url = `/entity?${new URLSearchParams(searchParams).toString()}`;
```

**Comment by schiller-manuel** [comment] 2024-05-16 21:25
"Any idea when it will no longer be experimental?"
not really. The problem is that converting a union to an intersection relies on TypeScript hacks that are not stable (see the original issue with too many union members for example).

for other questions please ask in our discord community at https://discord.com/channels/719702312431386674/1023930177224462388

**Closed** 2024-05-29 19:27 UTC

**Comment by chorobin** [comment] 2024-05-29 21:45
Looking for feedback on the way `useSearch` is merged with `strict: false` in the new versions so let us know
