### ISSUE TITLE
Typescript: useRouteContext with strict: false

### ISSUE THREAD

**Issue by maksymskuibida** [TanStack/router#1699] opened 2024-06-03 08:45 UTC
### Describe the bug

root context is undefined in useRouteContext with `strict: false`

If I do `from: '__root__' ` it works and cannot be undefined, but as far as I understand, root context cannot be undefined, so, even with `strict: false` root context properties should not be undefined.

### Your Example Website or App

typescript

### Steps to Reproduce the Bug or Issue

-

### Expected behavior

I expected that root context properties should not be undefined in useRouteContext({strict: false})

### Platform

-

**Comment by SeanCassiere** [comment] 2024-07-11 23:42
When using useRouterContext it must always have a `from` specifier. The issue with the router context being selectively undefined will be fixed with #1907. 

I'm closing this issue since there is no reproduction attached.

**Closed by SeanCassiere** 2024-07-11 23:42 UTC
