### ISSUE TITLE
[tsr-routes-manifest] Could not load tsr:routes-manifest (start)

### ISSUE THREAD

**Issue by Lukjuh** [TanStack/router#2199] opened 2024-08-27 18:03 UTC
### Describe the bug

I'm getting the following error when running npm run build on Windows.

```
 vinxi build

vinxi v0.4.1


⚙  Building your app...
removing C:/Users/Luukl/OneDrive/Bureaublad/testing/.vinxi/build/client


📦 Compiling client router...
vinxi building router client in client mode

♻️  Generating routes...
✅ Processed route in 70ms
vite v5.4.2 building for production...
[plugin:vite:resolve] [plugin vite:resolve] Module "fs" has been externalized for browser compatibility, imported by "C:/Users/Luukl/OneDrive/Bureaublad/testing/app/routes/index.tsx". See https://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
app/routes/index.tsx (8:27): Error when using sourcemap for reporting an error: Can't resolve original location of error.
app/routes/index.tsx (8:27): "promises" is not exported by "__vite-browser-external", imported by "app/routes/index.tsx".
virtual:$vinxi/handler/client (1:101): "default" is not exported by "app/client.tsx", imported by "virtual:$vinxi/handler/client".
✓ 107 modules transformed.
.vinxi/build/client/_build/server-functions-manifest.json    0.09 kB │ gzip:  0.10 kB
.vinxi/build/client/_build/.vite/manifest.json               0.17 kB │ gzip:  0.13 kB
.vinxi/build/client/_build/assets/client-UKPYRoIm.js       201.25 kB │ gzip: 65.41 kB
✓ built in 1.08s
✔ build done                                                                                                 19:59:18


📦 Compiling ssr router...
vinxi building router ssr in http mode

♻️  Regenerating routes...
✅ Processed route in 7ms
vite v5.4.2 building SSR bundle for production...
✓ 10 modules transformed.
x Build failed in 37ms

[19:59:18]  ERROR  [tsr-routes-manifest] Could not load tsr:routes-manifest (imported by node_modules/@tanstack/start/dist/esm/router-manifest/index.js): Cannot read properties of undefined (reading 'map')

  at Object.load (/C:/Users/Luukl/OneDrive/Bureaublad/testing/node_modules/@tanstack/start/dist/esm/config/index.js:381:46)
  at async PluginDriver.hookFirstAndGetPlugin (/C:/Users/Luukl/OneDrive/Bureaublad/testing/node_modules/rollup/dist/es/shared/node-entry.js:19813:28)
  at async /C:/Users/Luukl/OneDrive/Bureaublad/testing/node_modules/rollup/dist/es/shared/node-entry.js:18977:33
  at async Queue.work (/C:/Users/Luukl/OneDrive/Bureaublad/testing/node_modules/rollup/dist/es/shared/node-entry.js:20023:32)



[19:59:18]  ERROR  [tsr-routes-manifest] Could not load tsr:routes-manifest (imported by node_modules/@tanstack/start/dist/esm/router-manifest/index.js): Cannot read properties of undefined (reading 'map')
```

### Your Example Website or App

https://stackblitz.com/github/tanstack/router/tree/main/examples/react/start-basic?embed=1&theme=light&preset=node&file=src/main.tsx

### Steps to Reproduce the Bug or Issue

npm run build

### Expected behavior

should build successfully

### Platform

- OS: [Windows]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by schiller-manuel** [comment] 2024-08-27 18:28
duplicate of https://github.com/TanStack/router/issues/1889

**Closed by schiller-manuel** 2024-08-27 18:28 UTC
