### ISSUE TITLE
Clicking on a link triggers rendering of multiple components multiple times

### ISSUE THREAD

**Issue by zorzysty** [TanStack/router#1145] opened 2024-02-03 10:34 UTC
### Describe the bug

Given you have Root component with an outlet and two routes (Index and About), when you're on About and click on a link that navigates to Index, here is the console output of components being rendered:
![image](https://github.com/TanStack/router/assets/5398733/70749d57-1f6d-4f58-ad89-f6b388f647df)

My app has some very havy pages to navigate betwen (many thousands of components on a page), so rendering them multiple times causes serious performance issues.

I was able to reproduce this bug in aminimal setup possible using the quickstart code-based example from the docs. I stripped out preloading and strict mode to be sure they don't affect the outcome.

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-byhsle?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

1. Click between About and Home links
2. Notice the console output showing components that are being rendered

### Expected behavior

When clicking on Index I expect only Index component to be rendered, So instead of this console output:
![image](https://github.com/TanStack/router/assets/5398733/79c5c365-456a-4f6c-9676-8ea6442ae0d7)
I would expect to see only this:
![image](https://github.com/TanStack/router/assets/5398733/646f1cdc-b8c3-451e-b2b6-b3c6168c9217)

And I would certainly not expect the About component that I'm navigating away from to be rendered 4 times when clicking the Index link.

### Screenshots or Videos

https://github.com/TanStack/router/assets/5398733/117250e5-c59b-4543-b170-e7d002672949

### Platform

- OS: Linux and Windows
- Browser: Chrome, Firefox

**Comment by schiller-manuel** [comment] 2024-02-03 11:21
duplicate of #1112

**Closed** 2024-02-03 17:26 UTC
