### ISSUE TITLE
Screen flash white when using browser navigation

### ISSUE THREAD

**Issue by MariuzM** [TanStack/router#2562] opened 2024-10-17 05:39 UTC
### Which project does this relate to?

Router

### Describe the bug

Screen flashes white when using browser buttons to go back or forward
https://github.com/user-attachments/assets/61ede5a6-50c4-48c7-8486-65ea5c46406b

### Your Example Website or App

https://github.com/MariuzM/web-frameworks/tree/test-tsr-flashing-when-navigating-back/react-tsr/src/routes

### Steps to Reproduce the Bug or Issue

Click the navigation items it will work fine, but when you use browser to go back screen flash white, also same for browser forward. 

### Expected behavior

No flash pls

### Screenshots or Videos

https://github.com/user-attachments/assets/5da4ad9c-d2b5-4b00-8398-47712d41ea1c

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by schiller-manuel** [comment] 2024-10-17 22:00
you are using react 19, that's not supported right now.
also duplicate of https://github.com/TanStack/router/issues/2082

**Closed by schiller-manuel** 2024-10-17 22:00 UTC

**Comment by craftgear** [comment] 2025-02-26 04:52
@MariuzM Hi, is this problem solved on your side?

**Comment by schiller-manuel** [comment] 2025-02-26 08:21
@craftgear this particular issue was resolved. please open a new GitHub issue if you found a new one.

**Comment by craftgear** [comment] 2025-02-26 20:19
@schiller-manuel Gotcha!
