### ISSUE TITLE
Some route properties are undefined sometimes

### ISSUE THREAD

**Issue by lo1tuma** [TanStack/router#2231] opened 2024-08-30 13:06 UTC
### Describe the bug

When creating routes programmatically and accessing properties like `to` or `path` directly it happens that they are `undefined` although according to their type they are guaranteed to exist. This happens usually when using access a route directly without a router context. So when I am access e.g. `myRoute.to` in a react component that is wrapped in `RouterProvider` this is usually not a problem. When when I use `myRoute.to` somewhere else, e.g. not a react route then this error happens.

### Your Example Website or App

https://stackblitz.com/edit/github-yk78pg-fd4auw?file=README.md

### Steps to Reproduce the Bug or Issue

* create a route via `const myRoute = createRoute({ path: '/', /* ... */ })`;
* try to access `myRoute.to` or `myRoute.path`

### Expected behavior

I think it should be either fixed so that `to` is not `undefined` or the type should be adjusted to correctly reflect that this property could be `undefined`.

### Platform

- Version: `1.51.6`

**Comment by schiller-manuel** [comment] 2024-08-30 16:36
duplicate of #1423 
summary: you cannot use the route properties before router initialization is finished.

changing the types to include possible undefined might be an option.

**Comment by lo1tuma** [comment] 2024-08-30 18:23
> you cannot use the route properties before router initialization is finished.

I this case I think the type shouldn’t even expose those properties, because even a runtime check for `undefined` would never pass before the router is initialized. One approach that comes to my mind would to have an `UninitializedRoute<>` type which would represent the value that is returned by `createRoute()`. To get the actual initialized route, which requires the `router` to have been created, we could introduce a new method on the router to resolve that, so e.g.

```ts
const myUninitializedRoute = createRoute({ /* ... */}) // .to property doesn’t exist
const router = createRouter({ /* ... */ });
const myInitializedRoute = router.resolve(myUninitializedRoute); // .to property does exist
```

**Comment by schiller-manuel** [comment] 2024-08-30 18:29
@chorobin  what's your take on this?

**Comment by chorobin** [comment] 2024-08-31 06:28
It's not uncommon for us to have properties just for type purposes. I would say making them possibly `undefined` seems worse if most of the time these properties are used inside the router context. If they're not meant to be used outside, maybe there should be an exception

**Closed** 2024-08-31 17:38 UTC
